### ISSUE TITLE
cmor_axis

### ISSUE THREAD

**Issue by styteca** [PCMDI/cmor3_documentation#1]
Hello,
I don't see  cmor_axis in CMOR API documentation ??

**Comment by dnadeau4** [comment]
thanks, I am working on it today.

**Comment by dnadeau4** [comment]
I have updated the web site with ```cmor_axis()``` and ```cmor_grid()```.  I also recreated the PDF files with the new API information.  Thanks a lot for your comment, if you see anything else missing or misspelled just create a new issue.
