### ISSUE TITLE
Can't access CMOR docs on cmor.llnl.gov

### ISSUE THREAD

**Issue by simon-pinnock** [PCMDI/cmor3_documentation#128]
Hello,  

I'm trying to use CMOR3 to write satellite climate data records in obs4MIPs format, but I can't access several of the web pages on https://cmor.llnl.gov/.

I can access the Getting Started (https://cmor.llnl.gov/) and API pages (https://cmor.llnl.gov/mydoc_cmor3_api/), but none of the rest, such as Installation (https://cmor.llnl.gov/mydoc_cmor3_conda/) and Python Examples (https://cmor.llnl.gov/mydoc_cmor3_python/), nor even the Contact Us page (https://cmor.llnl.gov/mydoc_contacts/)

For these I get a 403 Forbidden error.

Thanks for any help.
Cheers
Simon

**Comment by mauzey1** [comment]
Our web server is currently undergoing maintenance.  We plan to have the documentation site back up once completed.

In the meantime, you can use the [PDF doc](https://github.com/PCMDI/cmor3_documentation/blob/master/pdf/mydoc.pdf).

**Comment by simon-pinnock** [comment]
Brilliant!  Thanks for the fast reply.
Cheers
Simon
