### ISSUE TITLE
CMOR3 doc site certificate issue

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor3_documentation#31]
@dnadeau4 @mattben it seems that the certificate for the https://cmor.llnl.gov site isn't correct, as below:
![cmorcertificateissue](https://cloud.githubusercontent.com/assets/3229632/23806775/e297221c-0577-11e7-9a7d-983b2361e07d.png)

**Comment by dnadeau4** [comment]
@durack1 Don't know what to do about this!!!  Is this the new normal?

**Comment by durack1** [comment]
@dnadeau4 I think we need to involve @mattben and @hoang1 on the certificate stuff

**Comment by ilovezfs** [comment]
Ping on this.

**Comment by dnadeau4** [comment]
Done
