### ISSUE TITLE
SSL incorrectly configured for cmor.llnl.gov

### ISSUE THREAD

**Issue by ilovezfs** [PCMDI/cmor3_documentation#32]
>cmor.llnl.gov uses an invalid security certificate. The certificate is only valid for the following names: pcmdi6.llnl.gov, aims.llnl.gov, cdp.llnl.gov, cf-pcmdi.llnl.gov, cf-trac.llnl.gov, icnwg.llnl.gov, esgf.llnl.gov, uvcdat.llnl.gov, uv-cdat.llnl.gov Error code: SSL_ERROR_BAD_CERT_DOMAIN

http://cmor.llnl.gov/ is redirecting to https://cmor.llnl.gov/ which is not a valid name for the certificate so it is impossible to visit the website without adding a security exception.

**Comment by durack1** [comment]
@ilovezfs this is a dupe of #31

**Comment by ilovezfs** [comment]
Thanks @durack1
