### ISSUE TITLE
Installation Guide Issues

### ISSUE THREAD

**Issue by ghost** [PCMDI/cmor3_documentation#39]
Hi, i have every step of your installation guide (using the github source) but i was facing some issues:

**1. i also had to install zlibrary form http://zlib.net/
2. i also had to install the m4 package (sudo apt-get install m4)
3. i also had to install python pip (sudo apt-get install python-pip)
4. using pip i needed to install numpy (sudo pip install numpy)
5. after compiling all the libraries i tried to import cmor and got following error:**
_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/CMOR-3.2-py2.7-linux-x86_64.egg/cmor/__init__.py", line 7, in <module>
    from cmor_const import *
  File "/usr/local/lib/python2.7/dist-packages/CMOR-3.2-py2.7-linux-x86_64.egg/cmor/cmor_const.py", line 1, in <module>
    import _cmor
ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory_

To solve this issue i had to add the path to die shared lib to LD_LIBRARY_PATH! (in my case: export LD_LIBRARY_PATH=$HOME/build/lib)

maybe this could be mentioned in the installation guide! 

Also most links to the dependencies are broken!
**HDF5:** https://www.hdfgroup.org/downloads/hdf5/source-code/
**UDUNITS2:** ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.25.tar.gz

i used a Ubuntu 16.04 LTS VM for compiling CMOR

best regards,
Florian

**Comment by doutriaux1** [comment]
@dnadeau4 we should update these instruction or discontinue non conda support

**Comment by doutriaux1** [comment]
documentation now reflects how to obtain correct env for building
