### ISSUE TITLE
"Control Vocabulary" should be named "Controlled Vocabulary"

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor3_documentation#55]
@dnadeau4 I think you should replace _control_ with **controlled** in several places of https://cmor.llnl.gov/mydoc_cmor3_CV/ and possibly other pages, in order to be consistent with the way @durack1 is using it on https://github.com/WCRP-CMIP/CMIP6_CVs

**Comment by mauzey1** [comment]
@doutriaux1 @durack1 There are several places that use the term "controlled vocabulary" but the parameter in the user input of CMOR is named `"_control_vocabulary_file"`

https://github.com/PCMDI/cmor/blob/e066e2b02bccde1104de3c18ad06c75f4cd70c0a/include/cmor.h#L191

https://github.com/PCMDI/cmor/blob/e066e2b02bccde1104de3c18ad06c75f4cd70c0a/Test/CMOR_input_example.json#L60

Should we change that parameter's name to match the documentation?

**Comment by durack1** [comment]
@mauzey1 sure, for consistency this sounds like a nice tweak
