### ISSUE TITLE
Corrections needed on examples

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor3_documentation#62]
1. The ncdump file for example 2 at https://cmor.llnl.gov/mydoc_cmor3_python/ has been corrupted: all of the upper-case letters have been made lower case.
2.  In most (all?) of the examples, the time coordinates are incorrect.  The calendar is set to "360-day", so January should be centered at 15 and February at 45; the bounds should be 0, 30, 60.
3.  The "branch_method", "branch_time_in_parent", and "branch_time_in_child" attributes should all be omitted.  If this is not possible, set branch_time_in_child = 0.0.  Both branch times must be double precision, not float.

**Comment by durack1** [comment]
@taylor13 this looks good to me, see below
![Screenshot 2024-08-29 at 3 06 35 PM](https://github.com/user-attachments/assets/1f05dbf4-b50c-4a26-9343-b830b3c4fbb3)

Will close
