### ISSUE TITLE
cannot subscribe to cmor mailing list 

### ISSUE THREAD

**Issue by chrisdane** [PCMDI/cmor3_documentation#74]
Hi

On `https://cmor.llnl.gov/mydoc_contacts/` its written to subscribe to the cmor mailing list you need to send a mail with the content `subscribe cmor` to `LISTSERV@listserv.llnl.gov`. However, if I do this, I receive a mail with the following content:
```
> |subscribe cmor|
Unknown command - "|SUBSCRIBE". Try HELP.
```

**Comment by mauzey1** [comment]
@chrisdane It looks like you got `|` characters in your email text.  I'm not sure how they got there since they don't show up on the contact page.

**Comment by chrisdane** [comment]
This did not help.
1. click "New Mail"
2. mail text: `subscribe cmor` (no title, no more text, no signature)
3. click "Send Mail"
4. receive mail from `LISTSERV@LISTSERV.LLNL.GOV` with subject `Output of your job "<firstname.familyname>"` with the mail text
```
> |subscribe cmor|
Unknown command - "|SUBSCRIBE". Try HELP.
```

**Comment by mauzey1** [comment]
Which email client are you using?  I am not able to replicate this problem using Outlook or Thunderbird.

@durack1 @sashakames @sterlingbaldwin Could you try subscribing to the CMOR mailing list following the above instructions?

**Comment by durack1** [comment]
@mauzey1 the steps above https://github.com/PCMDI/cmor3_documentation/issues/74#issuecomment-610781718 worked perfectly using a gmail account

**Comment by chrisdane** [comment]
I use Thunderbird 68.6.0 as mail client. 

I have just sent the subscription mail directly from the online access page of my mail account. That worked. Strange, but I am happy for now. 

Thanks a lot for your help and stay healthy
Chris

**Comment by durack1** [comment]
@chrisdane there have been a number of problems with Thunderbird reported, thanks for clarifying.

As the issue is resolved I will close the issue
