### ISSUE TITLE
Cannot install cmor3

### ISSUE THREAD

**Issue by EugeneRozanov** [PCMDI/cmor3_documentation#99]
I am not an experienced user, so I just followed the instructions. Everything went ok until "make" phase. The computer complains about the absence of several mathematical functions (e.g., atan, log10, and so on) in the one of c-written code. The community advised to add -lm flag at the link phase, but I cannot understand where exactly it should be done.  Any advice on how to change Makefile or something else?

E. Rozanov

**Comment by mauzey1** [comment]
@EugeneRozanov 
Which platform are you building CMOR on?  Mac or Linux?

Have you tried rerunning the configure step and then running `make install` again?

**Comment by EugeneRozanov** [comment]
I have LINUX, TCSH shell.
I repeateted the procedure 4 times and the result was always the same. I have also tried to compile my FORTRAN code. The compilation is OK but the program behave very strange and unpredictable. It looks like all cmor functions are corrupted.

I am very glad somebody answer.

E.

Sent from my Huawei phone


-------- Original message --------

**Comment by EugeneRozanov** [comment]
I moved to another computer and error with “ATAN” did not appear.
All test (make test_python) are ok, but test with fortran (make test_fortran) failed with

gfortran: error: unrecognized command line option ‘-fno-plt’

I could not find such option for gfortran and I do not now can it be substituted by something else.

Please, advise.

Eugene

I have LINUX, TCSH shell.
I repeateted the procedure 4 times and the result was always the same. I have also tried to compile my FORTRAN code. The compilation is OK but the program behave very strange and unpredictable. It looks like all cmor functions are corrupted.

I am very glad somebody answer.




E.

Sent from my Huawei phone


-------- Original message --------

**Comment by mauzey1** [comment]
@EugeneRozanov It might help if you post the output of `conda list` for your conda environment as well as the output for `make test_fortran`.

**Comment by EugeneRozanov** [comment]
Here they are. How to add

**Comment by mauzey1** [comment]
@EugeneRozanov I'm still not sure what is going wrong with your build.  The gfortran compiler not recognizing the option `-fno-plt` might indicate that an older version of gcc is being used.  Check your Makefile's `FC` and `CC` variables to see where the compilers are coming from.  Does running `make test_C` work?

**Comment by EugeneRozanov** [comment]
Thanks. I checked and corrected gcc. It works now.
E.
